"""The slotting objective: a surrogate you can search, not the thing you report.

There are two numbers in a slotting study and confusing them is the classic
mistake.

The **evaluation** number is simulated picker travel: take the order stream,
route every batch with a real routing policy, add up the metres. It is the
number that matters and the number that goes in the report. It is also useless
as a search objective, because evaluating one candidate assignment costs a full
routing pass over thousands of orders, and a pairwise-swap local search needs
tens of thousands of evaluations.

The **search** objective is a decomposable surrogate that a swap can be scored
against in O(neighbours):

    J = alpha * sum_i  f_i * d(depot, loc_i)                     [velocity]
      + beta  * sum_ij c_ij * d(loc_i, loc_j)                    [affinity]
      + gamma * sum_i  f_i * ergo_metres(level_i, weight_i)      [ergonomics]
      + delta * sum_families spread(family)                      [grouping]

which is a quadratic assignment problem: linear term pulls fast movers towards
the dock, quadratic term pulls co-ordered SKUs towards each other, and the two
genuinely fight. QAP is the right frame - it is also why nobody solves slotting
to optimality above toy sizes (Koopmans & Beckmann 1957; Frazelle 2016 ch. 8).

Everything is in metres, or metre-equivalents at the picker's walking speed, so
the four terms are commensurable.

``alpha`` and ``beta`` are **fitted, not tuned** - see
:mod:`slotting.calibration`, which regresses the change in routed travel on the
change in these features over move sets generated by the search itself. Three
more obvious ways of setting them are documented there along with how each one
fails, because each of them produced an objective that improved while measured
travel got worse.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Sequence

import numpy as np

from .assignment import Assignment
from .ergonomics import ErgonomicModel
from .layout import Warehouse
from .orders import OrderStream
from .skus import Catalog

__all__ = [
    "ObjectiveWeights",
    "SlottingObjective",
    "build_affinity_pairs",
    "tour_pick_weights",
]


@dataclass(frozen=True)
class ObjectiveWeights:
    """Relative weights of the four terms. All terms are already in metres."""

    velocity: float = 1.0
    affinity: float = 1.0
    ergonomics: float = 1.0
    grouping: float = 0.0
    depot_trip_factor: float = 2.0  # out and back
    lines_per_tour: float = 1.0  # divide the depot anchor across the tour


def build_affinity_pairs(
    stream: OrderStream,
    n_skus: int,
    top_k: int = 12,
    min_count: int = 2,
    normalise: str = "tour",
) -> list[tuple[int, int, float]]:
    """Sparsify the co-occurrence matrix to the ``top_k`` partners per SKU.

    The dense matrix is n_skus^2 and almost entirely noise: a pair seen twice in
    4,000 orders carries no signal but does carry a gradient, and the search
    will happily chase 400,000 of them. Keeping the strongest ``top_k`` partners
    per SKU turns the quadratic term into something with a few thousand entries,
    which is both faster and better behaved.

    ``normalise``:
      ``tour``  each order contributes ``2 / n_lines`` to every pair it
                contains, so the order's total pair weight is ``n_lines - 1``.
                That is the number of *edges* a tour through those picks
                actually has, which makes the quadratic term scale like a path
                length instead of like a complete graph. Raw counts overstate
                large orders by a factor of n/2 and are the reason a naive
                affinity term wrecks the velocity term when both are in the
                same objective. This is the default.
      ``count`` raw co-occurrence.
      ``lift``  count divided by the independence expectation, which promotes
                slow-moving pairs that always travel together. Useful when the
                fast movers are already handled by the velocity term.
    """
    if normalise == "tour":
        weighted_raw: dict[tuple[int, int], float] = {}
        seen_count: dict[tuple[int, int], int] = {}
        for order in stream:
            lines = sorted(set(order.lines))
            n = len(lines)
            if n < 2:
                continue
            w = 2.0 / n
            for a in range(n):
                for b in range(a + 1, n):
                    key = (lines[a], lines[b])
                    weighted_raw[key] = weighted_raw.get(key, 0.0) + w
                    seen_count[key] = seen_count.get(key, 0) + 1
        weighted = {k: v for k, v in weighted_raw.items() if seen_count[k] >= min_count}
        return _top_k_pairs(weighted, top_k)

    counts = stream.cooccurrence(min_count=min_count)
    if not counts:
        return []
    if normalise == "lift":
        line_counts = stream.line_counts()
        n_orders = max(float(len(stream)), 1.0)
        p = line_counts / n_orders
        weighted = {
            (i, j): c / max(p[i] * p[j] * n_orders, 1e-9) for (i, j), c in counts.items()
        }
    elif normalise == "count":
        weighted = {k: float(v) for k, v in counts.items()}
    else:
        raise ValueError(f"unknown normalisation {normalise!r}")
    return _top_k_pairs(weighted, top_k)


def _top_k_pairs(
    weighted: dict[tuple[int, int], float], top_k: int
) -> list[tuple[int, int, float]]:
    by_sku: dict[int, list[tuple[float, int]]] = {}
    for (i, j), w in weighted.items():
        by_sku.setdefault(i, []).append((w, j))
        by_sku.setdefault(j, []).append((w, i))

    kept: set[tuple[int, int]] = set()
    for i, partners in by_sku.items():
        partners.sort(reverse=True)
        for w, j in partners[:top_k]:
            kept.add((i, j) if i < j else (j, i))

    return [(i, j, float(weighted[(i, j)])) for (i, j) in sorted(kept)]


def tour_pick_weights(stream: OrderStream) -> np.ndarray:
    """Depot-anchor weight per SKU: ``w_i = sum over orders containing i of 2 / n_lines``.

    Raw pick frequency is the wrong weight for the linear term. A line in a
    ten-line order does not carry a full round trip to the dock; it carries a
    tenth of one, because the other nine lines are on the same tour. Weighting
    by ``2 / n_lines`` charges each line its share of the depot anchor, and
    makes the linear term a genuine estimate of metres rather than a ranking
    device. On this instance the two orderings differ for about a fifth of the
    catalogue, because basket size is correlated with SKU popularity.
    """
    w = np.zeros(stream.n_skus, dtype=float)
    for order in stream:
        lines = set(order.lines)
        if not lines:
            continue
        share = 2.0 / len(lines)
        for sku in lines:
            w[sku] += share
    return w


class SlottingObjective:
    """Evaluate and incrementally re-evaluate the surrogate objective."""

    def __init__(
        self,
        warehouse: Warehouse,
        catalog: Catalog,
        pick_rate: np.ndarray | None = None,
        affinity_pairs: list[tuple[int, int, float]] | None = None,
        weights: ObjectiveWeights | None = None,
        ergonomics: ErgonomicModel | None = None,
        line_rate: np.ndarray | None = None,
        calibration: object | None = None,
    ) -> None:
        self.warehouse = warehouse
        self.catalog = catalog
        self.weights = weights or ObjectiveWeights()
        self.ergo = ergonomics or ErgonomicModel()

        self.pick_rate = (
            np.asarray(pick_rate, dtype=float) if pick_rate is not None else catalog.picks.copy()
        )
        # Ergonomic cost is charged per pick *line*, not per depot-anchor share:
        # bending for a carton costs the same whether or not the picker is going
        # to that aisle anyway.
        self.line_rate = (
            np.asarray(line_rate, dtype=float) if line_rate is not None else self.pick_rate
        )
        self.calibration = calibration
        self.affinity_pairs = list(affinity_pairs or [])

        # Adjacency for O(deg) swap deltas.
        self._neighbours: list[np.ndarray] = [np.empty(0, dtype=np.int64)] * catalog.n_skus
        self._nweights: list[np.ndarray] = [np.empty(0, dtype=float)] * catalog.n_skus
        nb: dict[int, list[tuple[int, float]]] = {}
        for i, j, w in self.affinity_pairs:
            nb.setdefault(i, []).append((j, w))
            nb.setdefault(j, []).append((i, w))
        for s, lst in nb.items():
            self._neighbours[s] = np.asarray([x[0] for x in lst], dtype=np.int64)
            self._nweights[s] = np.asarray([x[1] for x in lst], dtype=float)

        # Location-indexed constants.
        self._depot_d = warehouse.depot_distance_vector()
        self._access = np.asarray(
            [warehouse.access_index(i) for i in range(warehouse.n_locations)], dtype=np.int64
        )
        self._access_matrix = warehouse.access_distance_matrix()

        # SKU x level ergonomic penalty in metres, weight-adjusted per SKU.
        c = warehouse.config
        heights = np.asarray(
            [self.ergo.height_of_level(l, c.level_height_m) for l in range(c.n_levels)]
        )
        self._ergo_metres = np.asarray(
            [
                [self.ergo.metres(h, float(w)) for h in heights]
                for w in catalog.case_weight
            ],
            dtype=float,
        )
        self._loc_level = np.asarray([loc.level for loc in warehouse.locations])

        self._alpha = (
            self.weights.velocity
            * self.weights.depot_trip_factor
            / max(self.weights.lines_per_tour, 1e-9)
        )
        self._beta = self.weights.affinity
        self._gamma = self.weights.ergonomics
        self._delta = self.weights.grouping

    # ------------------------------------------------------------------
    # full evaluation
    # ------------------------------------------------------------------
    def components(self, assignment: Assignment) -> dict[str, float]:
        loc = assignment.location_of
        if (loc < 0).any():
            raise ValueError("objective requires a complete assignment")
        velocity = self._alpha * float(np.dot(self.pick_rate, self._depot_d[loc]))
        ergo = self._gamma * float(
            np.dot(self.line_rate, self._ergo_metres[np.arange(len(loc)), self._loc_level[loc]])
        )
        affinity = 0.0
        if self.affinity_pairs:
            acc = self._access[loc]
            ii = np.asarray([p[0] for p in self.affinity_pairs], dtype=np.int64)
            jj = np.asarray([p[1] for p in self.affinity_pairs], dtype=np.int64)
            ww = np.asarray([p[2] for p in self.affinity_pairs], dtype=float)
            d = self._access_matrix[acc[ii], acc[jj]]
            affinity = self._beta * float(np.dot(ww, d))
        grouping = self._delta * self.family_spread(assignment) if self._delta else 0.0
        return {
            "velocity": velocity,
            "affinity": affinity,
            "ergonomics": ergo,
            "grouping": grouping,
            "total": velocity + affinity + ergo + grouping,
        }

    def total(self, assignment: Assignment) -> float:
        return self.components(assignment)["total"]

    def family_spread(self, assignment: Assignment) -> float:
        """Mean pick-weighted distance of each SKU from its family's centroid slot.

        Cheap proxy for "can a replenisher find the family". Not used by default
        (weight 0) but exposed because it is the term people ask for by name.
        """
        loc = assignment.location_of
        acc = self._access[loc]
        total = 0.0
        for fam in np.unique(self.catalog.family):
            members = np.flatnonzero(self.catalog.family == fam)
            if len(members) < 2:
                continue
            sub = self._access_matrix[np.ix_(acc[members], acc[members])]
            medoid = int(np.argmin(sub.sum(axis=1)))
            total += float(np.dot(self.pick_rate[members], sub[medoid]))
        return total

    # ------------------------------------------------------------------
    # incremental evaluation
    # ------------------------------------------------------------------
    def _linear_cost(self, sku: int, loc: int) -> float:
        return self._alpha * self.pick_rate[sku] * self._depot_d[loc] + self._gamma * (
            self.line_rate[sku] * self._ergo_metres[sku, self._loc_level[loc]]
        )

    def _affinity_cost(self, sku: int, loc: int, assignment: Assignment, exclude: int) -> float:
        nbrs = self._neighbours[sku]
        if nbrs.size == 0:
            return 0.0
        ws = self._nweights[sku]
        if exclude >= 0:
            mask = nbrs != exclude
            if not mask.all():
                nbrs = nbrs[mask]
                ws = ws[mask]
                if nbrs.size == 0:
                    return 0.0
        other_acc = self._access[assignment.location_of[nbrs]]
        d = self._access_matrix[self._access[loc], other_acc]
        return self._beta * float(np.dot(ws, d))

    def swap_delta(self, assignment: Assignment, sku_a: int, sku_b: int) -> float:
        """Change in objective from exchanging the locations of two SKUs.

        The ``a-b`` pair term, if the two are affinity neighbours, is invariant
        under the swap and is excluded from both sides.
        """
        la = int(assignment.location_of[sku_a])
        lb = int(assignment.location_of[sku_b])
        before = (
            self._linear_cost(sku_a, la)
            + self._linear_cost(sku_b, lb)
            + self._affinity_cost(sku_a, la, assignment, sku_b)
            + self._affinity_cost(sku_b, lb, assignment, sku_a)
        )
        after = (
            self._linear_cost(sku_a, lb)
            + self._linear_cost(sku_b, la)
            + self._affinity_cost(sku_a, lb, assignment, sku_b)
            + self._affinity_cost(sku_b, la, assignment, sku_a)
        )
        return after - before

    def move_delta(self, assignment: Assignment, sku: int, new_loc: int) -> float:
        """Change in objective from moving one SKU to an empty location."""
        old = int(assignment.location_of[sku])
        before = self._linear_cost(sku, old) + self._affinity_cost(sku, old, assignment, -1)
        after = self._linear_cost(sku, new_loc) + self._affinity_cost(
            sku, new_loc, assignment, -1
        )
        return after - before

    def commit(self) -> None:
        """No-op. Present so the search can treat every objective the same way.

        :class:`slotting.travel.TravelObjective` caches per-order distances and
        needs to be told when a move was accepted; the surrogate is stateless.
        """

    # ------------------------------------------------------------------
    def golden_zone_share(self, assignment: Assignment) -> float:
        """Share of picks taken from an ergonomically comfortable level."""
        c = self.warehouse.config
        good = np.asarray(
            [self.ergo.is_golden(l, c.level_height_m) for l in range(c.n_levels)]
        )
        levels = self._loc_level[assignment.location_of]
        return float(
            np.dot(self.line_rate, good[levels]) / max(self.line_rate.sum(), 1e-9)
        )
