"""SKU catalogue and the synthetic data-generating process behind it.

Everything in this repository is generated by code. The generator is written
to reproduce the four properties of a real forward-pick catalogue that actually
change what a slotting algorithm should do:

1. **Pareto popularity.** Pick frequency follows a Zipf-Mandelbrot law,
   ``p_i proportional to (i + q)^-s``. Real catalogues concentrate harder than
   people expect; the benchmark instance puts roughly half of all picks in the
   top 10% of SKUs, and the shape of that curve is what decides whether ABC
   slotting is worth anything.
2. **Cube and velocity are only weakly related.** The cases that move fastest
   are not the small ones. If cube and picks were correlated, cube-per-order
   index and pick-frequency ranking would give the same answer and there would
   be nothing to argue about. They are not, so they do not, and the argument is
   the interesting part (Heskett 1963; Frazelle 2016 ch. 8).
3. **Weight is density times cube, not an independent draw.** That is what
   makes the weight-by-level constraint bite on exactly the wrong SKUs: dense
   fast movers want the near, high, cheap slots and cannot have them.
4. **Families and hazmat classes.** Families drive order co-occurrence (see
   :mod:`slotting.orders`) and give the affinity methods something real to
   find. Hazmat classes are a small minority of SKUs that carry hard
   constraints, which is exactly the situation where a constraint-blind
   optimiser produces a beautiful, illegal answer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np

__all__ = [
    "SKU",
    "Catalog",
    "CatalogConfig",
    "generate_catalog",
    "HAZMAT_CLASSES",
    "hazmat_incompatible",
]

# A deliberately small, generic segregation table. Real segregation matrices
# come from the local regulator; the point here is that some pairs may not be
# stored close together, and one of them (flammable) may not be stored high.
HAZMAT_CLASSES: tuple[str, ...] = ("none", "flammable", "oxidizer", "corrosive")

_INCOMPATIBLE: frozenset[frozenset[str]] = frozenset(
    {
        frozenset({"flammable", "oxidizer"}),
        frozenset({"flammable", "corrosive"}),
        frozenset({"oxidizer", "corrosive"}),
    }
)


def hazmat_incompatible(a: str, b: str) -> bool:
    """True if two hazmat classes may not be stored within the separation distance."""
    if a == "none" or b == "none":
        return False
    return frozenset({a, b}) in _INCOMPATIBLE


@dataclass(frozen=True, slots=True)
class SKU:
    """One stock-keeping unit as the slotting problem sees it."""

    sku_id: int
    family: int
    picks_per_period: float  # expected pick lines per period
    units_per_pick: float  # average cases taken per line
    case_cube_m3: float
    case_weight_kg: float
    hazmat: str = "none"

    @property
    def unit_cube_velocity(self) -> float:
        """Cube shipped per period. The right ranking key when the constraint is cube."""
        return self.picks_per_period * self.units_per_pick * self.case_cube_m3

    @property
    def code(self) -> str:  # pragma: no cover - display only
        return f"SKU{self.sku_id:05d}"


@dataclass(frozen=True)
class CatalogConfig:
    """Parameters of the data-generating process."""

    n_skus: int = 900
    n_families: int = 18
    zipf_exponent: float = 0.92
    zipf_offset: float = 3.0
    total_picks_per_period: float = 40_000.0
    mean_units_per_pick: float = 1.9
    case_cube_median_m3: float = 0.022
    case_cube_log_sigma: float = 0.70
    density_median_kg_m3: float = 260.0
    density_log_sigma: float = 0.45
    cube_velocity_corr: float = -0.18  # weak, negative: big cases move a bit slower
    hazmat_share: float = 0.07


class Catalog:
    """An indexed collection of SKUs plus the vectorised views the solvers want."""

    def __init__(self, skus: Sequence[SKU], config: CatalogConfig | None = None) -> None:
        self.skus: tuple[SKU, ...] = tuple(skus)
        self.config = config
        self.picks = np.asarray([s.picks_per_period for s in self.skus], dtype=float)
        self.units_per_pick = np.asarray([s.units_per_pick for s in self.skus], dtype=float)
        self.case_cube = np.asarray([s.case_cube_m3 for s in self.skus], dtype=float)
        self.case_weight = np.asarray([s.case_weight_kg for s in self.skus], dtype=float)
        self.family = np.asarray([s.family for s in self.skus], dtype=np.int64)
        self.hazmat = np.asarray([s.hazmat for s in self.skus], dtype=object)
        self.cube_velocity = self.picks * self.units_per_pick * self.case_cube

    def __len__(self) -> int:
        return len(self.skus)

    def __getitem__(self, i: int) -> SKU:
        return self.skus[i]

    def __iter__(self):
        return iter(self.skus)

    @property
    def n_skus(self) -> int:
        return len(self.skus)

    def cases_per_slot(
        self,
        slot_cube_m3: float,
        max_cases: int = 60,
        max_weight_kg: float | None = None,
    ) -> np.ndarray:
        """How many cases of each SKU a pick face is filled to.

        Three limits, whichever binds first: the slot cube, a replenishment cap
        (a face is refilled by pallet or tote, not case by case), and the rack
        rating at floor level. Modelling only the cube limit is the mistake that
        produces 450 cases of a 3-litre item in one slot and a slot weight
        nothing on earth could lift.
        """
        caps = np.minimum(np.floor(slot_cube_m3 / self.case_cube), float(max_cases))
        if max_weight_kg is not None:
            caps = np.minimum(
                caps, np.floor(max_weight_kg / np.maximum(self.case_weight, 1e-6))
            )
        return np.maximum(caps, 1.0)

    def slot_weight(
        self,
        slot_cube_m3: float,
        max_cases: int = 60,
        max_weight_kg: float | None = None,
    ) -> np.ndarray:
        """Weight of a full slot of each SKU. This is what the level constraint sees."""
        return self.cases_per_slot(slot_cube_m3, max_cases, max_weight_kg) * self.case_weight

    def hazmat_indices(self) -> np.ndarray:
        return np.flatnonzero(self.hazmat != "none")

    def pick_share_curve(self) -> np.ndarray:
        """Cumulative share of picks when SKUs are sorted fastest-first."""
        order = np.argsort(-self.picks)
        return np.cumsum(self.picks[order]) / self.picks.sum()

    def concentration(self, sku_share: float = 0.20) -> float:
        """Share of picks contributed by the fastest ``sku_share`` of SKUs."""
        curve = self.pick_share_curve()
        k = max(1, int(round(sku_share * len(curve))))
        return float(curve[k - 1])

    def abc_classes(
        self, metric: str = "picks", thresholds: tuple[float, float] = (0.80, 0.95)
    ) -> np.ndarray:
        """Classic A/B/C split on cumulative share of the chosen metric."""
        values = self.metric(metric)
        order = np.argsort(-values)
        cum = np.cumsum(values[order]) / values.sum()
        classes = np.empty(len(values), dtype="<U1")
        for rank, idx in enumerate(order):
            if cum[rank] <= thresholds[0]:
                classes[idx] = "A"
            elif cum[rank] <= thresholds[1]:
                classes[idx] = "B"
            else:
                classes[idx] = "C"
        return classes

    def metric(self, name: str, slot_cube_m3: float = 1.0) -> np.ndarray:
        """Ranking metric by name.

        ``picks``  pick lines per period - the labour driver in a manual pick.
        ``cube``   cube shipped per period - the driver when replenishment,
                   not picking, is the bottleneck.
        ``coi``    Heskett's cube-per-order index: storage cube divided by pick
                   frequency, ranked *ascending*. Returned negated so that
                   "larger is better" holds for every metric here.
        """
        if name == "picks":
            return self.picks
        if name == "cube":
            return self.cube_velocity
        if name == "coi":
            storage_cube = np.maximum(self.case_cube, 1e-9) * self.cases_per_slot(slot_cube_m3)
            return -(storage_cube / np.maximum(self.picks, 1e-9))
        if name == "picks_per_cube":
            return self.picks / np.maximum(self.case_cube, 1e-9)
        raise ValueError(f"unknown ranking metric {name!r}")


def generate_catalog(config: CatalogConfig | None = None, seed: int = 11) -> Catalog:
    """Draw a reproducible synthetic catalogue."""
    cfg = config or CatalogConfig()
    rng = np.random.default_rng(seed)
    n = cfg.n_skus

    # Zipf-Mandelbrot popularity, then shuffled so that sku_id carries no
    # information. A generator that leaves the fast movers at low ids makes
    # "slot in SKU-id order" look accidentally good.
    ranks = np.arange(1, n + 1, dtype=float)
    weights = (ranks + cfg.zipf_offset) ** (-cfg.zipf_exponent)
    weights = weights / weights.sum()
    rng.shuffle(weights)
    picks = weights * cfg.total_picks_per_period
    picks = np.maximum(picks, 0.5)

    # Case cube, weakly (negatively) correlated with popularity via a Gaussian
    # copula on the log scale.
    z_pop = _to_normal_scores(picks, rng)
    z_ind = rng.standard_normal(n)
    rho = cfg.cube_velocity_corr
    z_cube = rho * z_pop + np.sqrt(max(0.0, 1.0 - rho * rho)) * z_ind
    case_cube = cfg.case_cube_median_m3 * np.exp(cfg.case_cube_log_sigma * z_cube)
    case_cube = np.clip(case_cube, 0.002, 0.90)

    density = cfg.density_median_kg_m3 * np.exp(
        cfg.density_log_sigma * rng.standard_normal(n)
    )
    case_weight = np.clip(case_cube * density, 0.15, 32.0)

    units = np.maximum(1.0, rng.gamma(shape=3.0, scale=cfg.mean_units_per_pick / 3.0, size=n))

    family = rng.integers(0, cfg.n_families, size=n)

    hazmat = np.full(n, "none", dtype=object)
    n_haz = int(round(cfg.hazmat_share * n))
    if n_haz:
        # Hazmat travels with families: a chemicals family is a chemicals
        # family. Choosing whole families keeps the segregation constraint
        # spatially clustered, which is what makes it bind.
        haz_families = rng.choice(
            cfg.n_families, size=max(1, cfg.n_families // 5), replace=False
        )
        pool = np.flatnonzero(np.isin(family, haz_families))
        if len(pool) == 0:  # pragma: no cover - defensive
            pool = np.arange(n)
        chosen = rng.choice(pool, size=min(n_haz, len(pool)), replace=False)
        classes = rng.choice(HAZMAT_CLASSES[1:], size=len(chosen))
        for idx, cls in zip(chosen, classes):
            hazmat[idx] = str(cls)

    skus = [
        SKU(
            sku_id=int(i),
            family=int(family[i]),
            picks_per_period=float(picks[i]),
            units_per_pick=float(units[i]),
            case_cube_m3=float(case_cube[i]),
            case_weight_kg=float(case_weight[i]),
            hazmat=str(hazmat[i]),
        )
        for i in range(n)
    ]
    return Catalog(skus, cfg)


def _to_normal_scores(values: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Rank-based inverse normal scores, used as the copula input."""
    from scipy.stats import norm

    n = len(values)
    jitter = rng.uniform(0, 1e-9, size=n)
    order = np.argsort(values + jitter)
    ranks = np.empty(n, dtype=float)
    ranks[order] = np.arange(1, n + 1, dtype=float)
    return norm.ppf(ranks / (n + 1.0))
