"""Instance data model and a synthetic instance generator.

Everything here is generated by code from a seed - there is no scraped or
proprietary data anywhere in this repository. The generator is written to
produce instances with the property that makes network design interesting: the
fixed-cost and transport terms are the same order of magnitude, so the optimal
number of DCs is genuinely in question rather than "all of them" or "one".

Units, stated once and used consistently:

* distance  km (great-circle, inflated by a road-circuity factor)
* weight    kg
* volume    units of finished goods per planning period (a month)
* money     currency units per planning period
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field, replace
from typing import Any

import numpy as np

from .geometry import haversine_km

__all__ = [
    "Site",
    "Facility",
    "Commodity",
    "Mode",
    "Lane",
    "Instance",
    "generate_instance",
]

_INF = float("inf")


@dataclass(frozen=True)
class Site:
    """A geographic node: supplier, plant, DC candidate, or demand zone."""

    id: str
    name: str
    lat: float
    lon: float
    kind: str

    @property
    def coords(self) -> tuple[float, float]:
        return (self.lat, self.lon)


@dataclass(frozen=True)
class Facility(Site):
    """A site with an open/close decision attached."""

    fixed_cost: float = 0.0
    #: Throughput ceiling in units per period when the facility is open.
    capacity: float = _INF
    #: Volume the site must carry *if it is opened at all* (0 disables).
    min_volume: float = 0.0
    #: Variable handling/production cost per unit flowing through the site.
    handling_cost: float = 0.0


@dataclass(frozen=True)
class Commodity:
    id: str
    name: str
    kg_per_unit: float


@dataclass(frozen=True)
class Mode:
    """A transport mode. Cost is affine in weight and distance.

    ``fixed_per_kg`` captures terminal/handling cost that does not scale with
    distance - it is what makes rail lose to road on short hauls even though
    its per-km rate is a third of road's.
    """

    id: str
    rate_per_kg_km: float
    fixed_per_kg: float = 0.0
    min_distance_km: float = 0.0
    max_distance_km: float = _INF
    transit_days_per_1000km: float = 1.6


@dataclass(frozen=True)
class Lane:
    origin: str
    dest: str
    mode: str
    distance_km: float
    cost_per_kg: float

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.origin, self.dest, self.mode)


@dataclass
class Instance:
    """A complete multi-echelon network design instance.

    Echelons: ``suppliers -> plants -> dcs -> zones``. Suppliers and zones are
    fixed; plants and DCs carry an opening decision.
    """

    name: str
    suppliers: list[Site]
    plants: list[Facility]
    dcs: list[Facility]
    zones: list[Site]
    commodities: list[Commodity]
    modes: list[Mode]
    #: (supplier_id, commodity_id) -> available units per period
    supply: dict[tuple[str, str], float]
    #: (zone_id, commodity_id) -> demand in units per period
    demand: dict[tuple[str, str], float]
    #: (plant_id, commodity_id) -> production cost per unit
    production_cost: dict[tuple[str, str], float]
    lanes: list[Lane]
    meta: dict[str, Any] = field(default_factory=dict)

    # -- lookups -------------------------------------------------------------

    def __post_init__(self) -> None:
        self._lane_index: dict[tuple[str, str, str], Lane] = {ln.key: ln for ln in self.lanes}
        self._site_index: dict[str, Site] = {}
        for s in (*self.suppliers, *self.plants, *self.dcs, *self.zones):
            self._site_index[s.id] = s
        self._commodity_index = {c.id: c for c in self.commodities}
        self._mode_index = {m.id: m for m in self.modes}

    @property
    def supplier_ids(self) -> list[str]:
        return [s.id for s in self.suppliers]

    @property
    def plant_ids(self) -> list[str]:
        return [p.id for p in self.plants]

    @property
    def dc_ids(self) -> list[str]:
        return [d.id for d in self.dcs]

    @property
    def zone_ids(self) -> list[str]:
        return [z.id for z in self.zones]

    @property
    def commodity_ids(self) -> list[str]:
        return [c.id for c in self.commodities]

    def site(self, site_id: str) -> Site:
        return self._site_index[site_id]

    def commodity(self, commodity_id: str) -> Commodity:
        return self._commodity_index[commodity_id]

    def mode(self, mode_id: str) -> Mode:
        return self._mode_index[mode_id]

    def lane(self, origin: str, dest: str, mode: str) -> Lane:
        return self._lane_index[(origin, dest, mode)]

    def lanes_by_echelon(self, origin_kind: str, dest_kind: str) -> list[Lane]:
        return [
            ln
            for ln in self.lanes
            if self._site_index[ln.origin].kind == origin_kind
            and self._site_index[ln.dest].kind == dest_kind
        ]

    def unit_cost(self, lane: Lane, commodity_id: str) -> float:
        """Transport cost of moving one unit of *commodity_id* down *lane*."""
        return lane.cost_per_kg * self._commodity_index[commodity_id].kg_per_unit

    def total_demand(self, commodity_id: str | None = None) -> float:
        if commodity_id is None:
            return float(sum(self.demand.values()))
        return float(sum(v for (_, k), v in self.demand.items() if k == commodity_id))

    def zone_demand(self, zone_id: str) -> float:
        return float(sum(v for (z, _), v in self.demand.items() if z == zone_id))

    def scaled_demand(self, multipliers: dict[str, float] | float) -> dict[tuple[str, str], float]:
        """Demand scaled per zone (dict) or globally (scalar)."""
        if isinstance(multipliers, (int, float)):
            return {k: v * float(multipliers) for k, v in self.demand.items()}
        return {
            (z, c): v * float(multipliers.get(z, 1.0)) for (z, c), v in self.demand.items()
        }

    def with_demand(self, demand: dict[tuple[str, str], float]) -> Instance:
        return replace(self, demand=dict(demand))

    def with_lane_cost_multiplier(self, multiplier: float) -> Instance:
        return replace(
            self,
            lanes=[replace(ln, cost_per_kg=ln.cost_per_kg * multiplier) for ln in self.lanes],
        )

    # -- validation ----------------------------------------------------------

    def validate(self) -> list[str]:
        """Return a list of structural problems; empty means structurally sane."""
        problems: list[str] = []
        for z in self.zones:
            for c in self.commodities:
                if self.demand.get((z.id, c.id), 0.0) > 0 and not any(
                    ln.dest == z.id for ln in self.lanes
                ):
                    problems.append(f"zone {z.id} has demand for {c.id} but no inbound lane")
        for d in self.dcs:
            if not any(ln.dest == d.id for ln in self.lanes):
                problems.append(f"DC {d.id} has no inbound lane and can never be used")
            if d.min_volume > d.capacity:
                problems.append(
                    f"DC {d.id} min_volume {d.min_volume:,.0f} exceeds capacity {d.capacity:,.0f}"
                )
        for c in self.commodities:
            dem = self.total_demand(c.id)
            plant_cap = sum(p.capacity for p in self.plants)
            if plant_cap < dem:
                problems.append(
                    f"commodity {c.id}: plant capacity {plant_cap:,.0f} < demand {dem:,.0f}"
                )
            sup = sum(v for (_, k), v in self.supply.items() if k == c.id)
            if sup < dem:
                problems.append(f"commodity {c.id}: supply {sup:,.0f} < demand {dem:,.0f}")
        return problems

    # -- serialisation -------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "suppliers": [asdict(s) for s in self.suppliers],
            "plants": [asdict(p) for p in self.plants],
            "dcs": [asdict(d) for d in self.dcs],
            "zones": [asdict(z) for z in self.zones],
            "commodities": [asdict(c) for c in self.commodities],
            "modes": [asdict(m) for m in self.modes],
            "supply": [[k[0], k[1], v] for k, v in self.supply.items()],
            "demand": [[k[0], k[1], v] for k, v in self.demand.items()],
            "production_cost": [[k[0], k[1], v] for k, v in self.production_cost.items()],
            "lanes": [asdict(ln) for ln in self.lanes],
            "meta": self.meta,
        }

    def to_json(self, indent: int = 1) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> Instance:
        return cls(
            name=payload["name"],
            suppliers=[Site(**s) for s in payload["suppliers"]],
            plants=[Facility(**p) for p in payload["plants"]],
            dcs=[Facility(**d) for d in payload["dcs"]],
            zones=[Site(**z) for z in payload["zones"]],
            commodities=[Commodity(**c) for c in payload["commodities"]],
            modes=[Mode(**m) for m in payload["modes"]],
            supply={(a, b): v for a, b, v in payload["supply"]},
            demand={(a, b): v for a, b, v in payload["demand"]},
            production_cost={(a, b): v for a, b, v in payload["production_cost"]},
            lanes=[Lane(**ln) for ln in payload["lanes"]],
            meta=payload.get("meta", {}),
        )

    def summary(self) -> str:
        return (
            f"{self.name}: {len(self.suppliers)} suppliers, {len(self.plants)} plants, "
            f"{len(self.dcs)} DC candidates, {len(self.zones)} zones, "
            f"{len(self.commodities)} commodities, {len(self.lanes)} lanes, "
            f"demand {self.total_demand():,.0f} units/period"
        )


# ---------------------------------------------------------------------------
# synthetic generator
# ---------------------------------------------------------------------------

# Anonymous metro anchors on a continental-scale landmass. Coordinates are
# arbitrary points in a lat/lon box, not real cities; the weights give the
# heavy-tailed demand concentration real networks have.
_METROS: tuple[tuple[str, float, float, float], ...] = (
    ("NE", 41.6, -73.5, 1.00),
    ("MA", 39.2, -76.9, 0.72),
    ("SE", 33.6, -84.2, 0.68),
    ("GL", 41.9, -87.9, 0.81),
    ("SC", 32.7, -96.9, 0.63),
    ("MT", 39.7, -104.9, 0.31),
    ("PN", 47.4, -122.2, 0.34),
    ("SW", 34.0, -118.2, 0.88),
)


def generate_instance(
    *,
    seed: int = 7,
    n_suppliers: int = 3,
    n_plants: int = 4,
    n_dcs: int = 8,
    n_zones: int = 25,
    n_commodities: int = 2,
    total_demand_units: float = 250_000.0,
    name: str = "synthetic-na",
    rail_min_distance_km: float = 900.0,
    capacity_slack: float = 1.45,
    dc_capacity_slack: float = 0.42,
    min_volume_fraction: float = 0.30,
) -> Instance:
    """Build a reproducible synthetic network design instance.

    Parameters worth knowing:

    ``capacity_slack``
        Total plant capacity as a multiple of total demand. Below ~1.15 the
        instance stops being a location problem and becomes a capacity problem.
    ``dc_capacity_slack``
        Each DC's throughput ceiling as a fraction of total demand, so no
        single DC can serve the whole country and at least two must open.
    ``min_volume_fraction``
        Minimum-volume-if-open threshold as a fraction of a DC's capacity. This
        is the constraint that turns an easy LP into a real MILP.
    """
    rng = np.random.default_rng(seed)

    commodity_specs = [
        ("SKU-A", "heavy durable", 12.0),
        ("SKU-B", "light consumable", 3.2),
        ("SKU-C", "bulky seasonal", 7.5),
    ]
    commodities = [
        Commodity(id=cid, name=nm, kg_per_unit=kg)
        for cid, nm, kg in commodity_specs[:n_commodities]
    ]

    # Rates are affine in distance: cost/kg = rate * km + fixed. The fixed term
    # is terminal/stop cost, and it is what creates a genuine mode split - rail
    # and truckload carry a heavy fixed charge and only win over distance.
    modes = [
        Mode("road", rate_per_kg_km=7.0e-5, fixed_per_kg=0.018, transit_days_per_1000km=1.6),
        Mode(
            "rail",
            rate_per_kg_km=2.6e-5,
            fixed_per_kg=0.085,
            min_distance_km=rail_min_distance_km,
            transit_days_per_1000km=3.4,
        ),
        # outbound: LTL wins below ~590 km, truckload above it
        Mode("ltl", rate_per_kg_km=1.75e-4, fixed_per_kg=0.030, max_distance_km=1400.0),
        Mode("tl", rate_per_kg_km=9.00e-5, fixed_per_kg=0.080, transit_days_per_1000km=1.5),
    ]

    def jitter(anchor: tuple[str, float, float, float], spread: float) -> tuple[float, float]:
        return (
            float(anchor[1] + rng.normal(0.0, spread)),
            float(anchor[2] + rng.normal(0.0, spread * 1.3)),
        )

    # -- demand zones: clustered around metro anchors, heavy-tailed weights --
    metro_w = np.array([m[3] for m in _METROS], dtype=float)
    metro_w = metro_w / metro_w.sum()
    zone_anchor_idx = rng.choice(len(_METROS), size=n_zones, p=metro_w)
    zones: list[Site] = []
    zone_weight = np.zeros(n_zones)
    for i, ai in enumerate(zone_anchor_idx):
        anchor = _METROS[int(ai)]
        lat, lon = jitter(anchor, 1.6)
        zones.append(Site(id=f"Z{i:02d}", name=f"{anchor[0]}-zone-{i:02d}", lat=lat, lon=lon, kind="zone"))
        # lognormal population weights: a few zones dominate, as in reality
        zone_weight[i] = anchor[3] * float(rng.lognormal(mean=0.0, sigma=0.55))
    zone_weight = zone_weight / zone_weight.sum()

    commodity_share = rng.dirichlet(np.full(len(commodities), 6.0))
    demand: dict[tuple[str, str], float] = {}
    for i, z in enumerate(zones):
        for j, c in enumerate(commodities):
            qty = total_demand_units * zone_weight[i] * commodity_share[j]
            demand[(z.id, c.id)] = float(round(qty, 1))

    total_by_commodity = {
        c.id: sum(v for (_, k), v in demand.items() if k == c.id) for c in commodities
    }
    grand_total = sum(total_by_commodity.values())

    # -- DC candidates: near metros, with a couple of deliberately awkward ones
    dc_anchor_idx = rng.choice(len(_METROS), size=n_dcs, replace=n_dcs > len(_METROS), p=metro_w)
    dcs: list[Facility] = []
    dc_cap = grand_total * dc_capacity_slack
    for i, ai in enumerate(dc_anchor_idx):
        anchor = _METROS[int(ai)]
        lat, lon = jitter(anchor, 2.2)
        # cheap-land sites sit further from demand; that tension is the point
        remoteness = float(rng.uniform(0.75, 1.25))
        fixed = 46_000.0 * remoteness * float(rng.uniform(0.85, 1.2))
        cap = dc_cap * float(rng.uniform(0.8, 1.25))
        dcs.append(
            Facility(
                id=f"DC{i:02d}",
                name=f"{anchor[0]}-dc-{i:02d}",
                lat=lat,
                lon=lon,
                kind="dc",
                fixed_cost=float(round(fixed, 0)),
                capacity=float(round(cap, 0)),
                min_volume=float(round(cap * min_volume_fraction, 0)),
                handling_cost=float(round(rng.uniform(0.28, 0.46), 4)),
            )
        )

    # -- plants: fewer, larger, spread across the landmass -------------------
    plants: list[Facility] = []
    plant_cap = grand_total * capacity_slack / n_plants
    for i in range(n_plants):
        anchor = _METROS[int(rng.integers(0, len(_METROS)))]
        lat, lon = jitter(anchor, 3.4)
        plants.append(
            Facility(
                id=f"PL{i:02d}",
                name=f"plant-{i:02d}",
                lat=lat,
                lon=lon,
                kind="plant",
                fixed_cost=float(round(255_000.0 * rng.uniform(0.8, 1.25), 0)),
                capacity=float(round(plant_cap * rng.uniform(0.85, 1.15), 0)),
                min_volume=0.0,
                handling_cost=0.0,
            )
        )

    production_cost: dict[tuple[str, str], float] = {}
    for p in plants:
        base = float(rng.uniform(0.93, 1.09))
        for c in commodities:
            production_cost[(p.id, c.id)] = float(round(base * (1.15 + 0.10 * c.kg_per_unit), 4))

    # -- suppliers: coastal/port-like, ample but not unlimited ---------------
    suppliers: list[Site] = []
    supply: dict[tuple[str, str], float] = {}
    port_anchors = [_METROS[7], _METROS[1], _METROS[6]]
    for i in range(n_suppliers):
        anchor = port_anchors[i % len(port_anchors)]
        lat, lon = jitter(anchor, 1.1)
        sid = f"SP{i:02d}"
        suppliers.append(Site(id=sid, name=f"supplier-{i:02d}", lat=lat, lon=lon, kind="supplier"))
        for c in commodities:
            supply[(sid, c.id)] = float(
                round(total_by_commodity[c.id] * (1.75 / n_suppliers) * rng.uniform(0.9, 1.3), 0)
            )

    # -- lanes ---------------------------------------------------------------
    lanes: list[Lane] = []

    def add_lane(o: Site, d: Site, mode: Mode, circuity: float) -> None:
        dist = circuity * haversine_km(o.lat, o.lon, d.lat, d.lon)
        if dist < mode.min_distance_km or dist > mode.max_distance_km:
            return
        cost_per_kg = mode.rate_per_kg_km * dist + mode.fixed_per_kg
        lanes.append(
            Lane(
                origin=o.id,
                dest=d.id,
                mode=mode.id,
                distance_km=float(round(dist, 1)),
                cost_per_kg=float(round(cost_per_kg, 6)),
            )
        )

    road, rail, ltl, truckload = modes[0], modes[1], modes[2], modes[3]
    for s in suppliers:
        for p in plants:
            add_lane(s, p, road, 1.12)
            add_lane(s, p, rail, 1.10)
    for p in plants:
        for d in dcs:
            add_lane(p, d, road, 1.17)
            add_lane(p, d, rail, 1.14)
    for d in dcs:
        for z in zones:
            add_lane(d, z, ltl, 1.22)
            add_lane(d, z, truckload, 1.22)

    inst = Instance(
        name=name,
        suppliers=suppliers,
        plants=plants,
        dcs=dcs,
        zones=zones,
        commodities=commodities,
        modes=modes,
        supply=supply,
        demand=demand,
        production_cost=production_cost,
        lanes=lanes,
        meta={
            "seed": seed,
            "total_demand_units": float(grand_total),
            "generator": "netdesign.instances.generate_instance",
        },
    )
    return inst


def demand_scenarios(
    instance: Instance,
    *,
    n_scenarios: int = 12,
    seed: int = 11,
    national_sigma: float = 0.20,
    regional_sigma: float = 0.22,
    zone_sigma: float = 0.18,
    growth_drift: float = 0.0,
) -> tuple[list[dict[tuple[str, str], float]], np.ndarray]:
    """Sample demand scenarios from a three-level shock model.

    ``multiplier(zone) = 1 + national + regional(metro) + idiosyncratic(zone)``

    The three levels are not decoration. Independent per-zone noise averages
    out across 25 zones, the stochastic optimum collapses onto the mean-value
    optimum, and VSS comes back as exactly zero - which is why so many
    published VSS numbers are zero and convince nobody. The variance that
    actually stresses a network is the part that does *not* diversify:

    * the **national** factor moves total volume against fixed capacity, which
      is what drives the open/close hedge;
    * the **regional** factor moves volume between metros, which is what drives
      *where* to hedge;
    * the **zone** factor is the diversifiable part, and it is included mainly
      to show that it does not matter.

    Returns the scenario demand vectors and equal probabilities.
    """
    rng = np.random.default_rng(seed)
    anchors = sorted({z.name.split("-")[0] for z in instance.zones})
    scenarios: list[dict[tuple[str, str], float]] = []
    for _ in range(n_scenarios):
        national = float(rng.normal(0.0, national_sigma))
        regional = {a: float(rng.normal(0.0, regional_sigma)) for a in anchors}
        mult: dict[str, float] = {}
        for z in instance.zones:
            shock = national + regional[z.name.split("-")[0]] + float(rng.normal(0.0, zone_sigma))
            mult[z.id] = float(max(0.05, 1.0 + growth_drift + shock))
        scenarios.append(instance.scaled_demand(mult))
    probs = np.full(n_scenarios, 1.0 / n_scenarios)
    return scenarios, probs
