"""scmplatform -- production plumbing for supply chain forecasting models.

Data contracts, point-in-time features, a model registry, a backtest gate for CI, and
drift/decision-quality monitoring. Everything runs on synthetic data generated by
:mod:`scmplatform.datagen`.
"""

from .backtest import (
    BacktestResult,
    ChallengerDecision,
    Gate,
    GateResult,
    champion_challenger,
    check_gate,
    rolling_backtest,
    wmape,
)
from .contracts import (
    ColumnSpec,
    ContractDiff,
    DataContract,
    ValidationReport,
    demand_panel_contract,
    diff_contracts,
    validate,
)
from .datagen import PanelConfig, inject_quality_faults, make_panel
from .decisions import DecisionQuality, InventoryEconomics, evaluate_decisions
from .features import (
    FeatureSpec,
    SkewReport,
    audit_features,
    build_features,
    default_specs,
    detect_skew,
    knowledge_time_check,
    leaky_specs,
    truncation_check,
)
from .monitoring import (
    drift_over_time,
    drift_report,
    prediction_drift,
    psi,
    slice_performance,
)
from .registry import ModelCard, ModelRegistry, RegistryError

__version__ = "0.1.0"

__all__ = [
    "BacktestResult",
    "ChallengerDecision",
    "ColumnSpec",
    "ContractDiff",
    "DataContract",
    "DecisionQuality",
    "FeatureSpec",
    "Gate",
    "GateResult",
    "InventoryEconomics",
    "ModelCard",
    "ModelRegistry",
    "PanelConfig",
    "RegistryError",
    "SkewReport",
    "ValidationReport",
    "audit_features",
    "build_features",
    "champion_challenger",
    "check_gate",
    "default_specs",
    "demand_panel_contract",
    "detect_skew",
    "diff_contracts",
    "drift_over_time",
    "drift_report",
    "evaluate_decisions",
    "inject_quality_faults",
    "knowledge_time_check",
    "leaky_specs",
    "make_panel",
    "prediction_drift",
    "psi",
    "rolling_backtest",
    "slice_performance",
    "truncation_check",
    "validate",
    "wmape",
    "__version__",
]
